let eventflags = [];

eventflags.push({id: 171, name: "Godrick's Great Rune"});
eventflags.push({id: 172, name: "Radahn's Great Rune"});
eventflags.push({id: 173, name: "Morgott's Great Rune"});
eventflags.push({id: 174, name: "Rykard's Great Rune"});
eventflags.push({id: 175, name: "Mohg's Great Rune"});
eventflags.push({id: 176, name: "Malenia's Great Rune"});
eventflags.push({id: 197, name: "Great Rune of the Unborn"});


eventflags.push({id: 9100, name: "Godrick the Grafted - Stormveil Castle"});
eventflags.push({id: 9101, name: "Margit, the Fell Omen - Stormveil Castle"});
eventflags.push({id: 9103, name: "Grafted Scion - Chapel of Anticipation"});
eventflags.push({id: 9104, name: "Morgott, the Omen King - Leyndell"});
eventflags.push({id: 9105, name: "Godfrey, First Elden Lord - Leyndell"});
eventflags.push({id: 9106, name: "Sir Gideon Ofnir, the All-Knowing - Leyndell"});
eventflags.push({id: 9107, name: "Hoarah Loux - Leyndell"});
eventflags.push({id: 9108, name: "Astel, Naturalborn of the Void - Lake of Rot"});
eventflags.push({id: 9109, name: "Dragonkin Soldier of Nokstella - Ainsel River"});
eventflags.push({id: 9111, name: "Lichdragon Fortissax"});
eventflags.push({id: 9112, name: "Mohg"});
eventflags.push({id: 9115, name: "Dragonlord Placidusax"});
eventflags.push({id: 9116, name: "Maliketh"});
eventflags.push({id: 9118, name: "Rennala"});
eventflags.push({id: 9119, name: "Loretta"});
eventflags.push({id: 9120, name: "Malenia"});
eventflags.push({id: 9122, name: "Rykard, Lord of Blasphemy"});
eventflags.push({id: 9123, name: "Elden Beast"});
eventflags.push({id: 9130, name: "Starscourge Radahn"});
eventflags.push({id: 9131, name: "Fire Giant"});
eventflags.push({id: 9133, name: "Regal Ancestor Spirit"});
eventflags.push({id: 9134, name: "Dragonkin Soldier - Lake of Rot"});
eventflags.push({id: 9135, name: "Fia's Champion - Deeproot Depths"});
eventflags.push({id: 9182, name: "Elemer of the Briar"});
eventflags.push({id: 9184, name: "Commander Niall"});


eventflags.push({id: 9500, name: "Mending Rune of Perfect Order"});
eventflags.push({id: 9502, name: "Mending Rune of the Death-Prince"});
eventflags.push({id: 9504, name: "Mending Rune of the Fell Curse"});


eventflags.push({id: 60000, name: "Flask of Crimson Tears"});
eventflags.push({id: 60020, name: "Flask of Wondrous Physick"});
eventflags.push({id: 60100, name: "Spectral Steed Whistle"});
eventflags.push({id: 60110, name: "Spirit Calling Bell"});
eventflags.push({id: 60120, name: "Crafting Kit"});
eventflags.push({id: 60130, name: "Whetstone Knife"});
eventflags.push({id: 60140, name: "Tailoring Tools"});
eventflags.push({id: 60150, name: "Golden Tailoring Tools"});
eventflags.push({id: 60210, name: "Tarnished's Wizened Finger"});
eventflags.push({id: 60220, name: "Tarnished's Furled Finger"});
eventflags.push({id: 60230, name: "Small Golden Effigy"});
eventflags.push({id: 60240, name: "Duelist's Furled Finger"});
eventflags.push({id: 60250, name: "Small Red Effigy"});
eventflags.push({id: 60270, name: "Bloody Finger"});
eventflags.push({id: 60280, name: "White Cipher Ring"});
eventflags.push({id: 60290, name: "Blue Cipher Ring"});
eventflags.push({id: 60300, name: "Taunter's Tongue"});
eventflags.push({id: 60310, name: "Finger Severer"});


eventflags.push({id: 60400, name: "Memory Stone - World"});
eventflags.push({id: 60410, name: "Memory Stone - World"});
eventflags.push({id: 60420, name: "Memory Stone - World"});
eventflags.push({id: 60430, name: "Memory Stone - World"});
eventflags.push({id: 60440, name: "Memory Stone - Red Wolf of Radagon"});
eventflags.push({id: 60450, name: "Memory Stone - Demi-Human Queen Maggie"});
eventflags.push({id: 60460, name: "Memory Stone - World"});
eventflags.push({id: 60470, name: "Memory Stone - Twin Maiden Husks"});


eventflags.push({id: 60500, name: "Talisman Pouch - Finger Reader Enia - Godfrey"});
eventflags.push({id: 60510, name: "Talisman Pouch - Margit Kill"});
eventflags.push({id: 60520, name: "Talisman Pouch - Finger Reader Enia - 2 Great Runes"});


eventflags.push({id: 62010, name: "Map: Limgrave, West"});
eventflags.push({id: 62011, name: "Map: Weeping Peninsula"});
eventflags.push({id: 62012, name: "Map: Limgrave, East"});
eventflags.push({id: 62020, name: "Map: Liurnia, East"});
eventflags.push({id: 62021, name: "Map: Liurnia, North"});
eventflags.push({id: 62022, name: "Map: Liurnia, West"});
eventflags.push({id: 62030, name: "Map: Altus Plateau"});
eventflags.push({id: 62031, name: "Map: Leyndell, Royal Capital"});
eventflags.push({id: 62032, name: "Map: Mt. Gelmir"});
eventflags.push({id: 62040, name: "Map: Caelid"});
eventflags.push({id: 62041, name: "Map: Dragonbarrow"});
eventflags.push({id: 62050, name: "Map: Mountaintops of the Giants, West"});
eventflags.push({id: 62051, name: "Map: Mountaintops of the Giants, East"});
eventflags.push({id: 62060, name: "Map: Ainsel River"});
eventflags.push({id: 62061, name: "Map: Lake of Rot"});
eventflags.push({id: 62063, name: "Map: Siofra River"});
eventflags.push({id: 62062, name: "Map: Mohgwyn Palace"});
eventflags.push({id: 62064, name: "Map: Deeproot Depths"});
eventflags.push({id: 62052, name: "Map: Consecrated Snowfield"});


eventflags.push({id: 65000, name: "Crimsonspill Crystal Tear"});
eventflags.push({id: 65010, name: "Greenspill Crystal Tear"});
eventflags.push({id: 65020, name: "Crimson Crystal Tear"});
eventflags.push({id: 65030, name: "Crimson Crystal Tear"});
eventflags.push({id: 65040, name: "Cerulean Crystal Tear"});
eventflags.push({id: 65050, name: "Cerulean Crystal Tear"});
eventflags.push({id: 65060, name: "Speckled Hardtear"});
eventflags.push({id: 65070, name: "Crimson Bubbletear"});
eventflags.push({id: 65080, name: "Opaline Bubbletear"});
eventflags.push({id: 65090, name: "Crimsonburst Crystal Tear"});
eventflags.push({id: 65100, name: "Greenburst Crystal Tear"});
eventflags.push({id: 65110, name: "Opaline Hardtear"});
eventflags.push({id: 65120, name: "Winged Crystal Tear"});
eventflags.push({id: 65130, name: "Thorny Cracked Tear"});
eventflags.push({id: 65140, name: "Spiked Cracked Tear"});
eventflags.push({id: 65150, name: "Windy Crystal Tear"});
eventflags.push({id: 65160, name: "Ruptured Crystal Tear"});
eventflags.push({id: 65170, name: "Ruptured Crystal Tear"});
eventflags.push({id: 65180, name: "Leaden Hardtear"});
eventflags.push({id: 65190, name: "Twiggy Cracked Tear"});
eventflags.push({id: 65200, name: "Crimsonwhorl Bubbletear"});
eventflags.push({id: 65210, name: "Strength-knot Crystal Tear"});
eventflags.push({id: 65220, name: "Dexterity-knot Crystal Tear"});
eventflags.push({id: 65230, name: "Intelligence-knot Crystal Tear"});
eventflags.push({id: 65240, name: "Faith-knot Crystal Tear"});
eventflags.push({id: 65250, name: "Cerulean Hidden Tear"});
eventflags.push({id: 65260, name: "Stonebarb Cracked Tear"});
eventflags.push({id: 65270, name: "Purifying Crystal Tear"});
eventflags.push({id: 65280, name: "Flame-Shrouding Cracked Tear"});
eventflags.push({id: 65290, name: "Magic-Shrouding Cracked Tear"});
eventflags.push({id: 65300, name: "Lightning-Shrouding Cracked Tear"});
eventflags.push({id: 65310, name: "Holy-Shrouding Cracked Tear"});


eventflags.push({id: 65610, name: "Iron Whetblade"});
eventflags.push({id: 65640, name: "Red-Hot Whetblade"});
eventflags.push({id: 65660, name: "Sanctified Whetblade"});
eventflags.push({id: 65680, name: "Glintstone Whetblade"});
eventflags.push({id: 65720, name: "Black Whetblade"});


eventflags.push({id: 65810, name: "Ash of War: Impaling Thrust "});
eventflags.push({id: 65811, name: "Ash of War: Piercing Fang "});
eventflags.push({id: 65812, name: "Ash of War: Spinning Slash "});
eventflags.push({id: 65813, name: "Ash of War: Repeating Thrust "});
eventflags.push({id: 65814, name: "Ash of War: Double Slash "});
eventflags.push({id: 65815, name: "Ash of War: Unsheathe "});
eventflags.push({id: 65816, name: "Ash of War: Sword Dance "});
eventflags.push({id: 65818, name: "Ash of War: Quickstep "});
eventflags.push({id: 65819, name: "Ash of War: Bloodhound's Step "});
eventflags.push({id: 65820, name: "Ash of War: Lion's Claw "});
eventflags.push({id: 65821, name: "Ash of War: Stamp (Upward Cut) "});
eventflags.push({id: 65822, name: "Ash of War: Stamp (Sweep) "});
eventflags.push({id: 65823, name: "Ash of War: Wild Strikes "});
eventflags.push({id: 65824, name: "Ash of War: Earthshaker "});
eventflags.push({id: 65825, name: "Ash of War: Kick "});
eventflags.push({id: 65826, name: "Ash of War: Ground Slam "});
eventflags.push({id: 65827, name: "Ash of War: Hoarah Loux's Earthshaker "});
eventflags.push({id: 65828, name: "Ash of War: Barbaric Roar "});
eventflags.push({id: 65829, name: "Ash of War: War Cry "});
eventflags.push({id: 65830, name: "Ash of War: Troll's Roar "});
eventflags.push({id: 65831, name: "Ash of War: Braggart's Roar "});
eventflags.push({id: 65832, name: "Ash of War: Endure "});
eventflags.push({id: 65833, name: "Ash of War: Charge Forth "});
eventflags.push({id: 65834, name: "Ash of War: Square Off "});
eventflags.push({id: 65835, name: "Ash of War: Giant Hunt "});
eventflags.push({id: 65836, name: "Ash of War: Spinning Strikes "});
eventflags.push({id: 65837, name: "Ash of War: Storm Assault "});
eventflags.push({id: 65838, name: "Ash of War: Stormcaller "});
eventflags.push({id: 65839, name: "Ash of War: Storm Blade "});
eventflags.push({id: 65840, name: "Ash of War: Vacuum Slice "});
eventflags.push({id: 65841, name: "Ash of War: Storm Stomp "});
eventflags.push({id: 65842, name: "Ash of War: Determination "});
eventflags.push({id: 65843, name: "Ash of War: Royal Knight's Resolve "});
eventflags.push({id: 65844, name: "Ash of War: Prelate's Charge "});
eventflags.push({id: 65845, name: "Ash of War: Eruption "});
eventflags.push({id: 65846, name: "Ash of War: Flaming Strike "});
eventflags.push({id: 65847, name: "Ash of War: Black Flame Tornado "});
eventflags.push({id: 65848, name: "Ash of War: Flame of the Redmanes "});
eventflags.push({id: 65849, name: "Ash of War: Thunderbolt "});
eventflags.push({id: 65850, name: "Ash of War: Lightning Slash "});
eventflags.push({id: 65851, name: "Ash of War: Lightning Ram "});
eventflags.push({id: 65852, name: "Ash of War: Loretta's Slash "});
eventflags.push({id: 65853, name: "Ash of War: Spinning Weapon "});
eventflags.push({id: 65854, name: "Ash of War: Glintblade Phalanx "});
eventflags.push({id: 65855, name: "Ash of War: Glintstone Pebble "});
eventflags.push({id: 65856, name: "Ash of War: Gravitas "});
eventflags.push({id: 65857, name: "Ash of War: Carian Grandeur "});
eventflags.push({id: 65858, name: "Ash of War: Carian Greatsword "});
eventflags.push({id: 65859, name: "Ash of War: Waves of Darkness "});
eventflags.push({id: 65860, name: "Ash of War: Cragblade "});
eventflags.push({id: 65861, name: "Ash of War: Sacred Blade "});
eventflags.push({id: 65862, name: "Ash of War: Prayerful Strike "});
eventflags.push({id: 65863, name: "Ash of War: Golden Land "});
eventflags.push({id: 65864, name: "Ash of War: Sacred Ring of Light "});
eventflags.push({id: 65865, name: "Ash of War: Golden Slam "});
eventflags.push({id: 65866, name: "Ash of War: Golden Vow "});
eventflags.push({id: 65867, name: "Ash of War: Sacred Order "});
eventflags.push({id: 65868, name: "Ash of War: Shared Order "});
eventflags.push({id: 65869, name: "Ash of War: Beast's Roar "});
eventflags.push({id: 65870, name: "Ash of War: Phantom Slash "});
eventflags.push({id: 65871, name: "Ash of War: Spectral Lance "});
eventflags.push({id: 65872, name: "Ash of War: Raptor of the Mists "});
eventflags.push({id: 65873, name: "Ash of War: White Shadow's Lure "});
eventflags.push({id: 65874, name: "Ash of War: Poison Moth Flight "});
eventflags.push({id: 65875, name: "Ash of War: Poisonous Mist "});
eventflags.push({id: 65876, name: "Ash of War: Blood Tax "});
eventflags.push({id: 65877, name: "Ash of War: Bloody Slash "});
eventflags.push({id: 65878, name: "Ash of War: Lifesteal Fist "});
eventflags.push({id: 65879, name: "Ash of War: Blood Blade "});
eventflags.push({id: 65880, name: "Ash of War: Assassin's Gambit "});
eventflags.push({id: 65881, name: "Ash of War: Seppuku "});
eventflags.push({id: 65882, name: "Ash of War: Ice Spear "});
eventflags.push({id: 65883, name: "Ash of War: Chilling Mist "});
eventflags.push({id: 65884, name: "Ash of War: Hoarfrost Stomp "});
eventflags.push({id: 65885, name: "Ash of War: No Skill "});
eventflags.push({id: 65886, name: "Ash of War: Shield Bash "});
eventflags.push({id: 65887, name: "Ash of War: Shield Crash "});
eventflags.push({id: 65888, name: "Ash of War: Barricade Shield "});
eventflags.push({id: 65889, name: "Ash of War: Parry "});
eventflags.push({id: 65890, name: "Ash of War: Carian Retaliation "});
eventflags.push({id: 65891, name: "Ash of War: Storm Wall "});
eventflags.push({id: 65892, name: "Ash of War: Golden Parry "});
eventflags.push({id: 65893, name: "Ash of War: Thops's Barrier "});
eventflags.push({id: 65894, name: "Ash of War: Holy Ground "});
eventflags.push({id: 65895, name: "Ash of War: Vow of the Indomitable "});
eventflags.push({id: 65896, name: "Ash of War: Barrage "});
eventflags.push({id: 65897, name: "Ash of War: Mighty Shot "});
eventflags.push({id: 65898, name: "Ash of War: Sky Shot "});
eventflags.push({id: 65899, name: "Ash of War: Through and Through "});
eventflags.push({id: 65900, name: "Ash of War: Enchanted Shot "});
eventflags.push({id: 65901, name: "Ash of War: Rain of Arrows "});


eventflags.push({id: 66000, name: "Cracked Pot"});
eventflags.push({id: 66010, name: "Cracked Pot"});
eventflags.push({id: 66020, name: "Cracked Pot"});
eventflags.push({id: 66030, name: "Cracked Pot"});
eventflags.push({id: 66040, name: "Cracked Pot"});
eventflags.push({id: 66050, name: "Cracked Pot"});
eventflags.push({id: 66060, name: "Cracked Pot"});
eventflags.push({id: 66070, name: "Cracked Pot"});
eventflags.push({id: 66080, name: "Cracked Pot"});
eventflags.push({id: 66090, name: "Cracked Pot"});
eventflags.push({id: 66100, name: "Cracked Pot"});
eventflags.push({id: 66110, name: "Cracked Pot"});
eventflags.push({id: 66120, name: "Cracked Pot"});
eventflags.push({id: 66130, name: "Cracked Pot"});
eventflags.push({id: 66140, name: "Cracked Pot"});
eventflags.push({id: 66150, name: "Cracked Pot"});
eventflags.push({id: 66160, name: "Cracked Pot"});
eventflags.push({id: 66170, name: "Cracked Pot"});
eventflags.push({id: 66180, name: "Cracked Pot"});
eventflags.push({id: 66190, name: "Cracked Pot"});


eventflags.push({id: 66400, name: "Ritual Pot"});
eventflags.push({id: 66410, name: "Ritual Pot"});
eventflags.push({id: 66420, name: "Ritual Pot"});
eventflags.push({id: 66430, name: "Ritual Pot"});
eventflags.push({id: 66440, name: "Ritual Pot"});
eventflags.push({id: 66450, name: "Ritual Pot"});
eventflags.push({id: 66460, name: "Ritual Pot"});
eventflags.push({id: 66470, name: "Ritual Pot"});
eventflags.push({id: 66480, name: "Ritual Pot"});
eventflags.push({id: 66490, name: "Ritual Pot"});


eventflags.push({id: 66700, name: "Perfume Bottle"});
eventflags.push({id: 66710, name: "Perfume Bottle"});
eventflags.push({id: 66720, name: "Perfume Bottle"});
eventflags.push({id: 66730, name: "Perfume Bottle"});
eventflags.push({id: 66740, name: "Perfume Bottle"});
eventflags.push({id: 66750, name: "Perfume Bottle"});
eventflags.push({id: 66760, name: "Perfume Bottle"});
eventflags.push({id: 66770, name: "Perfume Bottle"});
eventflags.push({id: 66780, name: "Perfume Bottle"});
eventflags.push({id: 66790, name: "Perfume Bottle"});


eventflags.push({id: 67000, name: "Nomadic Warrior's Cookbook [1]"});
eventflags.push({id: 67110, name: "Nomadic Warrior's Cookbook [2]"});
eventflags.push({id: 67010, name: "Nomadic Warrior's Cookbook [3]"});
eventflags.push({id: 67800, name: "Nomadic Warrior's Cookbook [4]"});
eventflags.push({id: 67830, name: "Nomadic Warrior's Cookbook [5]"});
eventflags.push({id: 67020, name: "Nomadic Warrior's Cookbook [6]"});
eventflags.push({id: 67050, name: "Nomadic Warrior's Cookbook [7]"});
eventflags.push({id: 67880, name: "Nomadic Warrior's Cookbook [8]"});
eventflags.push({id: 67430, name: "Nomadic Warrior's Cookbook [9]"});
eventflags.push({id: 67030, name: "Nomadic Warrior's Cookbook [10]"});
eventflags.push({id: 67220, name: "Nomadic Warrior's Cookbook [11]"});
eventflags.push({id: 67060, name: "Nomadic Warrior's Cookbook [12]"});
eventflags.push({id: 67080, name: "Nomadic Warrior's Cookbook [13]"});
eventflags.push({id: 67870, name: "Nomadic Warrior's Cookbook [14]"});
eventflags.push({id: 67900, name: "Nomadic Warrior's Cookbook [15]"});
eventflags.push({id: 67290, name: "Nomadic Warrior's Cookbook [16]"});
eventflags.push({id: 67100, name: "Nomadic Warrior's Cookbook [17]"});
eventflags.push({id: 67270, name: "Nomadic Warrior's Cookbook [18]"});
eventflags.push({id: 67070, name: "Nomadic Warrior's Cookbook [19]"});
eventflags.push({id: 67230, name: "Nomadic Warrior's Cookbook [20]"});
eventflags.push({id: 67120, name: "Nomadic Warrior's Cookbook [21]"});
eventflags.push({id: 67890, name: "Nomadic Warrior's Cookbook [22]"});
eventflags.push({id: 67090, name: "Nomadic Warrior's Cookbook [23]"});
eventflags.push({id: 67910, name: "Nomadic Warrior's Cookbook [24]"});

eventflags.push({id: 67200, name: "Armorer's Cookbook [1]"});
eventflags.push({id: 67210, name: "Armorer's Cookbook [2]"});
eventflags.push({id: 67280, name: "Armorer's Cookbook [3]"});
eventflags.push({id: 67260, name: "Armorer's Cookbook [4]"});
eventflags.push({id: 67310, name: "Armorer's Cookbook [5]"});
eventflags.push({id: 67300, name: "Armorer's Cookbook [6]"});
eventflags.push({id: 67250, name: "Armorer's Cookbook [7]"});

eventflags.push({id: 67410, name: "Glintstone Craftsman's Cookbook [1]"});
eventflags.push({id: 67450, name: "Glintstone Craftsman's Cookbook [2]"});
eventflags.push({id: 67480, name: "Glintstone Craftsman's Cookbook [3]"});
eventflags.push({id: 67400, name: "Glintstone Craftsman's Cookbook [4]"});
eventflags.push({id: 67420, name: "Glintstone Craftsman's Cookbook [5]"});
eventflags.push({id: 67460, name: "Glintstone Craftsman's Cookbook [6]"});
eventflags.push({id: 67470, name: "Glintstone Craftsman's Cookbook [7]"});
eventflags.push({id: 67440, name: "Glintstone Craftsman's Cookbook [8]"});

eventflags.push({id: 67610, name: "Missionary's Cookbook [1]"});
eventflags.push({id: 67600, name: "Missionary's Cookbook [2]"});
eventflags.push({id: 67650, name: "Missionary's Cookbook [3]"});
eventflags.push({id: 67640, name: "Missionary's Cookbook [4]"});
eventflags.push({id: 67630, name: "Missionary's Cookbook [5]"});
eventflags.push({id: 67130, name: "Missionary's Cookbook [6]"});
eventflags.push({id: 68230, name: "Missionary's Cookbook [7]"});

eventflags.push({id: 68000, name: "Ancient Dragon Apostle's Cookbook [1]"});
eventflags.push({id: 68010, name: "Ancient Dragon Apostle's Cookbook [2]"});
eventflags.push({id: 68030, name: "Ancient Dragon Apostle's Cookbook [3]"});
eventflags.push({id: 68020, name: "Ancient Dragon Apostle's Cookbook [4]"});

eventflags.push({id: 67840, name: "Perfumer's Cookbook [1]"});
eventflags.push({id: 67850, name: "Perfumer's Cookbook [2]"});
eventflags.push({id: 67860, name: "Perfumer's Cookbook [3]"});
eventflags.push({id: 67920, name: "Perfumer's Cookbook [4]"});

eventflags.push({id: 68200, name: "Fevor's Cookbook [1]"});
eventflags.push({id: 68220, name: "Fevor's Cookbook [2]"});
eventflags.push({id: 68210, name: "Fevor's Cookbook [3]"});

eventflags.push({id: 68400, name: "Frenzied's Cookbook [1]"});
eventflags.push({id: 68410, name: "Frenzied's Cookbook [2]"});

eventflags.push({id: 82001, name: "Underground Map"});

eventflags.push({id: 270750, name: "Remembrance of the Grafted"});
eventflags.push({id: 270760, name: "Remembrance of the Starscourge"});
eventflags.push({id: 270770, name: "Remembrance of the Omen King"});
eventflags.push({id: 270780, name: "Remembrance of the Blasphemous"});
eventflags.push({id: 270790, name: "Remembrance of the Rot Goddess"});
eventflags.push({id: 270800, name: "Remembrance of the Full Moon Queen"});
eventflags.push({id: 270810, name: "Remembrance of the Blood Lord"});
eventflags.push({id: 270850, name: "Remembrance of the Black Blade"});
eventflags.push({id: 270860, name: "Remembrance of Hoarah Loux"});
eventflags.push({id: 270870, name: "Remembrance of the Dragonlord"});
eventflags.push({id: 270880, name: "Remembrance of the Lichdragon"});
eventflags.push({id: 270890, name: "Remembrance of the Fire Giant"});
eventflags.push({id: 270900, name: "Remembrance of the Regal Ancestor"});
eventflags.push({id: 270910, name: "Elden Remembrance"});
eventflags.push({id: 270920, name: "Remembrance of the Naturalborn"});


eventflags.push({id: 290000, name: "Axe of Godrick"});
eventflags.push({id: 290010, name: "Grafted Dragon"});
eventflags.push({id: 290020, name: "Starscourge Greatsword"});
eventflags.push({id: 290030, name: "Lion Greatbow"});
eventflags.push({id: 290040, name: "Morgott's Cursed Sword"});
eventflags.push({id: 290050, name: "Regal Omen Bairn"});
eventflags.push({id: 290060, name: "Blasphemous Blade"});
eventflags.push({id: 290070, name: "Rykard's Rancor"});
eventflags.push({id: 290080, name: "Hand of Malenia"});
eventflags.push({id: 290090, name: "Scarlet Aeonia"});
eventflags.push({id: 290100, name: "Mohgwyn's Sacred Spear"});
eventflags.push({id: 290110, name: "Bloodboon"});
eventflags.push({id: 290120, name: "Maliketh's Black Blade"});
eventflags.push({id: 290130, name: "Black Blade"});
eventflags.push({id: 290140, name: "Axe of Godfrey"});
eventflags.push({id: 290150, name: "Ash of War: Hoarah Loux's Earthshaker"});
eventflags.push({id: 290160, name: "Dragon King's Cragblade"});
eventflags.push({id: 290170, name: "Placidusax's Ruin"});
eventflags.push({id: 290180, name: "Carian Regal Scepter"});
eventflags.push({id: 290190, name: "Rennala's Full Moon"});
eventflags.push({id: 290200, name: "Fortissax's Lightning Spear"});
eventflags.push({id: 290210, name: "Death Lightning"});
eventflags.push({id: 290220, name: "Giant's Red Braid"});
eventflags.push({id: 290230, name: "Burn"});
eventflags.push({id: 290240, name: "Winged Greathorn"});
eventflags.push({id: 290250, name: "Ancestral Spirit's Horn"});
eventflags.push({id: 290260, name: "Marika's Hammer"});
eventflags.push({id: 290270, name: "Sacred Relic Sword"});
eventflags.push({id: 290280, name: "Bastard's Stars"});
eventflags.push({id: 290290, name: "Ash of War: Waves of Darkness"});


eventflags.push({id: 290500, name: "Dragonfire"});
eventflags.push({id: 290510, name: "Dragonice"});
eventflags.push({id: 290520, name: "Glintstone Breath"});
eventflags.push({id: 290530, name: "Rotten Breath"});
eventflags.push({id: 290540, name: "Agheel's Flame"});
eventflags.push({id: 290550, name: "Borealis's Mist"});
eventflags.push({id: 290560, name: "Smarag's Glintstone Breath"});
eventflags.push({id: 290570, name: "Ekzykes's Decay"});

eventflags.push({id: 290750, name: "Dragonclaw"});
eventflags.push({id: 290760, name: "Dragonmaw"});
eventflags.push({id: 290770, name: "Magma Breath"});
eventflags.push({id: 290780, name: "Theodorix's Magma"});
eventflags.push({id: 290790, name: "Greyoll's Roar"});


eventflags.push({id: 11109745, name: "Bone Peddler's Bell Bearing"});
eventflags.push({id: 11109746, name: "Meat Peddler's Bell Bearing"});
eventflags.push({id: 11109747, name: "Medicine Peddler's Bell Bearing"});
eventflags.push({id: 11109748, name: "Gravity Stone Peddler's Bell Bearing"});
eventflags.push({id: 11109751, name: "Smithing-Stone Miner's Bell Bearing [1]"});
eventflags.push({id: 11109752, name: "Smithing-Stone Miner's Bell Bearing [2]"});
eventflags.push({id: 11109753, name: "Smithing-Stone Miner's Bell Bearing [3]"});
eventflags.push({id: 11109754, name: "Smithing-Stone Miner's Bell Bearing [4]"});
eventflags.push({id: 11109755, name: "Somberstone Miner's Bell Bearing [1]"});
eventflags.push({id: 11109756, name: "Somberstone Miner's Bell Bearing [2]"});
eventflags.push({id: 11109757, name: "Somberstone Miner's Bell Bearing [3]"});
eventflags.push({id: 11109758, name: "Somberstone Miner's Bell Bearing [4]"});
eventflags.push({id: 11109759, name: "Somberstone Miner's Bell Bearing [5]"});
eventflags.push({id: 11109760, name: "Glovewort Picker's Bell Bearing [1]"});
eventflags.push({id: 11109761, name: "Glovewort Picker's Bell Bearing [2]"});
eventflags.push({id: 11109762, name: "Glovewort Picker's Bell Bearing [3]"});
eventflags.push({id: 11109763, name: "Ghost-Glovewort Picker's Bell Bearing [1]"});
eventflags.push({id: 11109764, name: "Ghost-Glovewort Picker's Bell Bearing [2]"});
eventflags.push({id: 11109765, name: "Ghost-Glovewort Picker's Bell Bearing [3]"});

eventflags.push({id: 71000, name: "[Stormveil Castle] Godrick the Grafted"});
eventflags.push({id: 71001, name: "[Stormveil Castle] Margit, the Fell Omen"});
eventflags.push({id: 71002, name: "[Stormveil Castle] Castleward Tunnel"});
eventflags.push({id: 71003, name: "[Stormveil Castle] Gateside Chamber"});
eventflags.push({id: 71004, name: "[Stormveil Castle] Stormveil Cliffside"});
eventflags.push({id: 71005, name: "[Stormveil Castle] Rampart Tower"});
eventflags.push({id: 71006, name: "[Stormveil Castle] Liftside Chamber"});
eventflags.push({id: 71007, name: "[Stormveil Castle] Secluded Cell"});
eventflags.push({id: 71008, name: "[Stormveil Castle] Stormveil Main Gate"});
eventflags.push({id: 71100, name: "[Leyndell, Royal Capital] Elden Throne"});
eventflags.push({id: 71101, name: "[Leyndell, Royal Capital] Erdtree Sanctuary"});
eventflags.push({id: 71102, name: "[Leyndell, Royal Capital] East Capital Rampart"});
eventflags.push({id: 71103, name: "[Leyndell, Royal Capital] Lower Capital Church"});
eventflags.push({id: 71104, name: "[Leyndell, Royal Capital] Avenue Balcony"});
eventflags.push({id: 71105, name: "[Leyndell, Royal Capital] West Capital Rampart"});
eventflags.push({id: 71107, name: "[Leyndell, Royal Capital] Queen's Bedchamber"});
eventflags.push({id: 71108, name: "[Leyndell, Royal Capital] Fortified Manor, First Floor"});
eventflags.push({id: 71109, name: "[Leyndell, Royal Capital] Divine Bridge"});
eventflags.push({id: 71120, name: "[Leyndell, Ashen Capital] Elden Throne"});
eventflags.push({id: 71121, name: "[Leyndell, Ashen Capital] Erdtree Sanctuary"});
eventflags.push({id: 71122, name: "[Leyndell, Ashen Capital] East Capital Rampart"});
eventflags.push({id: 71123, name: "[Leyndell, Ashen Capital] Leyndell, Capital of Ash"});
eventflags.push({id: 71124, name: "[Leyndell, Ashen Capital] Queen's Bedchamber"});
eventflags.push({id: 71125, name: "[Leyndell, Ashen Capital] Divine Bridge"});
eventflags.push({id: 71190, name: "[Roundtable Hold] Table of Lost Grace"});
eventflags.push({id: 71210, name: "[Ainsel River] Dragonkin Soldier of Nokstella"});
eventflags.push({id: 71211, name: "[Ainsel River] Ainsel River Well Depths"});
eventflags.push({id: 71212, name: "[Ainsel River] Ainsel River Sluice Gate"});
eventflags.push({id: 71213, name: "[Ainsel River] Ainsel River Downstream"});
eventflags.push({id: 71214, name: "[Ainsel River Main] Ainsel River Main"});
eventflags.push({id: 71215, name: "[Ainsel River Main] Nokstella, Eternal City"});
eventflags.push({id: 71216, name: "[Lake of Rot] Lake of Rot Shoreside"});
eventflags.push({id: 71218, name: "[Lake of Rot] Grand Cloister"});
eventflags.push({id: 71219, name: "[Ainsel River Main] Nokstella Waterfall Basin"});
eventflags.push({id: 71220, name: "[Nokron, Eternal City] Great Waterfall Basin"});
eventflags.push({id: 71221, name: "[Nokron, Eternal City] Mimic Tear"});
eventflags.push({id: 71222, name: "[Siofra River] Siofra River Bank"});
eventflags.push({id: 71223, name: "[Siofra River] Worshippers' Woods"});
eventflags.push({id: 71224, name: "[Nokron, Eternal City] Ancestral Woods"});
eventflags.push({id: 71225, name: "[Nokron, Eternal City] Aqueduct-Facing Cliffs"});
eventflags.push({id: 71226, name: "[Nokron, Eternal City] Night's Sacred Ground"});
eventflags.push({id: 71227, name: "[Siofra River] Below the Well"});
eventflags.push({id: 71230, name: "[Deeproot Depths] Prince of Death's Throne"});
eventflags.push({id: 71231, name: "[Deeproot Depths] Root-Facing Cliffs"});
eventflags.push({id: 71232, name: "[Deeproot Depths] Great Waterfall Crest"});
eventflags.push({id: 71233, name: "[Deeproot Depths] Deeproot Depths"});
eventflags.push({id: 71234, name: "[Deeproot Depths] The Nameless Eternal City"});
eventflags.push({id: 71235, name: "[Deeproot Depths] Across the Roots"});
eventflags.push({id: 71240, name: "[Ainsel River] Astel, Naturalborn of the Void"});
eventflags.push({id: 71250, name: "[Mohgwyn Palace] Cocoon of the Empyrean"});
eventflags.push({id: 71251, name: "[Mohgwyn Palace] Palace Approach Ledge-Road"});
eventflags.push({id: 71252, name: "[Mohgwyn Palace] Dynasty Mausoleum Entrance"});
eventflags.push({id: 71253, name: "[Mohgwyn Palace] Dynasty Mausoleum Midpoint"});
eventflags.push({id: 71270, name: "[Siofra River] Siofra River Well Depths"});
eventflags.push({id: 71271, name: "[Nokron, Eternal City] Nokron, Eternal City"});
eventflags.push({id: 71300, name: "[Crumbling Farum Azula] Maliketh, the Black Blade"});
eventflags.push({id: 71301, name: "[Crumbling Farum Azula] Dragonlord Placidusax"});
eventflags.push({id: 71302, name: "[Crumbling Farum Azula] Dragon Temple Altar"});
eventflags.push({id: 71303, name: "[Crumbling Farum Azula] Crumbling Beast Grave"});
eventflags.push({id: 71304, name: "[Crumbling Farum Azula] Crumbling Beast Grave Depths"});
eventflags.push({id: 71305, name: "[Crumbling Farum Azula] Tempest-Facing Balcony"});
eventflags.push({id: 71306, name: "[Crumbling Farum Azula] Dragon Temple"});
eventflags.push({id: 71307, name: "[Crumbling Farum Azula] Dragon Temple Transept"});
eventflags.push({id: 71308, name: "[Crumbling Farum Azula] Dragon Temple Lift"});
eventflags.push({id: 71309, name: "[Crumbling Farum Azula] Dragon Temple Rooftop"});
eventflags.push({id: 71310, name: "[Crumbling Farum Azula] Beside the Great Bridge"});
eventflags.push({id: 71400, name: "[Academy of Raya Lucaria] Raya Lucaria Grand Library"});
eventflags.push({id: 71401, name: "[Academy of Raya Lucaria] Debate Parlor"});
eventflags.push({id: 71402, name: "[Academy of Raya Lucaria] Church of the Cuckoo"});
eventflags.push({id: 71403, name: "[Academy of Raya Lucaria] Schoolhouse Classroom"});
eventflags.push({id: 71500, name: "[Elphael, Brace of the Haligtree] Malenia, Goddess of Rot"});
eventflags.push({id: 71501, name: "[Elphael, Brace of the Haligtree] Prayer Room"});
eventflags.push({id: 71502, name: "[Elphael, Brace of the Haligtree] Elphael Inner Wall"});
eventflags.push({id: 71503, name: "[Elphael, Brace of the Haligtree] Drainage Channel"});
eventflags.push({id: 71504, name: "[Elphael, Brace of the Haligtree] Haligtree Roots"});
eventflags.push({id: 71505, name: "[Miquella's Haligtree] Haligtree Promenade"});
eventflags.push({id: 71506, name: "[Miquella's Haligtree] Haligtree Canopy"});
eventflags.push({id: 71507, name: "[Miquella's Haligtree] Haligtree Town"});
eventflags.push({id: 71508, name: "[Miquella's Haligtree] Haligtree Town Plaza"});
eventflags.push({id: 71600, name: "[Volcano Manor] Rykard, Lord of Blasphemy"});
eventflags.push({id: 71601, name: "[Volcano Manor] Temple of Eiglay"});
eventflags.push({id: 71602, name: "[Volcano Manor] Volcano Manor"});
eventflags.push({id: 71603, name: "[Volcano Manor] Prison Town Church"});
eventflags.push({id: 71604, name: "[Volcano Manor] Guest Hall"});
eventflags.push({id: 71605, name: "[Volcano Manor] Audience Pathway"});
eventflags.push({id: 71606, name: "[Volcano Manor] Abductor Virgin"});
eventflags.push({id: 71607, name: "[Volcano Manor] Subterranean Inquisition Chamber"});
eventflags.push({id: 71800, name: "[Stranded Graveyard] Cave of Knowledge"});
eventflags.push({id: 71801, name: "[Stranded Graveyard] Stranded Graveyard"});
eventflags.push({id: 71900, name: "[Elden Throne] Fractured Marika"});
eventflags.push({id: 73000, name: "[Weeping Peninsula] Tombsward Catacombs"});
eventflags.push({id: 73001, name: "[Weeping Peninsula] Impaler's Catacombs"});
eventflags.push({id: 73002, name: "[Limgrave] Stormfoot Catacombs"});
eventflags.push({id: 73003, name: "[Liurnia of the Lakes] Road's End Catacombs"});
eventflags.push({id: 73004, name: "[Limgrave] Murkwater Catacombs"});
eventflags.push({id: 73005, name: "[Liurnia of the Lakes] Black Knife Catacombs"});
eventflags.push({id: 73006, name: "[Liurnia of the Lakes] Cliffbottom Catacombs"});
eventflags.push({id: 73007, name: "[Mt. Gelmir] Wyndham Catacombs"});
eventflags.push({id: 73008, name: "[Altus Plateau] Sainted Hero's Grave"});
eventflags.push({id: 73009, name: "[Mt. Gelmir] Gelmir Hero's Grave"});
eventflags.push({id: 73010, name: "[Capital Outskirts] Auriza Hero's Grave"});
eventflags.push({id: 73011, name: "[Stormhill] Deathtouched Catacombs"});
eventflags.push({id: 73012, name: "[Altus Plateau] Unsightly Catacombs"});
eventflags.push({id: 73013, name: "[Capital Outskirts] Auriza Side Tomb"});
eventflags.push({id: 73014, name: "[Caelid] Minor Erdtree Catacombs"});
eventflags.push({id: 73015, name: "[Caelid] Caelid Catacombs"});
eventflags.push({id: 73016, name: "[Caelid] War-Dead Catacombs"});
eventflags.push({id: 73017, name: "[Flame Peak] Giant-Conquering Hero's Grave"});
eventflags.push({id: 73018, name: "[Flame Peak] Giants' Mountaintop Catacombs"});
eventflags.push({id: 73019, name: "[Consecrated Snowfield] Consecrated Snowfield Catacombs"});
eventflags.push({id: 73020, name: "[Forbidden Lands] Hidden Path to the Haligtree"});
eventflags.push({id: 73100, name: "[Limgrave] Murkwater Cave"});
eventflags.push({id: 73101, name: "[Weeping Peninsula] Earthbore Cave"});
eventflags.push({id: 73102, name: "[Weeping Peninsula] Tombsward Cave"});
eventflags.push({id: 73103, name: "[Limgrave] Groveside Cave"});
eventflags.push({id: 73104, name: "[Liurnia of the Lakes] Stillwater Cave"});
eventflags.push({id: 73105, name: "[Liurnia of the Lakes] Lakeside Crystal Cave"});
eventflags.push({id: 73106, name: "[Liurnia of the Lakes] Academy Crystal Cave"});
eventflags.push({id: 73107, name: "[Mt. Gelmir] Seethewater Cave"});
eventflags.push({id: 73109, name: "[Mt. Gelmir] Volcano Cave"});
eventflags.push({id: 73110, name: "[Greyoll's Dragonbarrow] Dragonbarrow Cave"});
eventflags.push({id: 73111, name: "[Greyoll's Dragonbarrow] Sellia Hideaway"});
eventflags.push({id: 73112, name: "[Consecrated Snowfield] Cave of the Forlorn"});
eventflags.push({id: 73115, name: "[Limgrave] Coastal Cave"});
eventflags.push({id: 73117, name: "[Limgrave] Highroad Cave"});
eventflags.push({id: 73118, name: "[Altus Plateau] Perfumer's Grotto"});
eventflags.push({id: 73119, name: "[Altus Plateau] Sage's Cave"});
eventflags.push({id: 73120, name: "[Caelid] Abandoned Cave"});
eventflags.push({id: 73121, name: "[Caelid] Gaol Cave"});
eventflags.push({id: 73122, name: "[Mountaintops of the Giants] Spiritcaller's Cave"});
eventflags.push({id: 73200, name: "[Weeping Peninsula] Morne Tunnel"});
eventflags.push({id: 73201, name: "[Limgrave] Limgrave Tunnels"});
eventflags.push({id: 73202, name: "[Liurnia of the Lakes] Raya Lucaria Crystal Tunnel"});
eventflags.push({id: 73204, name: "[Altus Plateau] Old Altus Tunnel"});
eventflags.push({id: 73205, name: "[Altus Plateau] Altus Tunnel"});
eventflags.push({id: 73207, name: "[Caelid] Gael Tunnel"});
eventflags.push({id: 73207, name: "[Caelid] Rear Gael Tunnel Entrance"});
eventflags.push({id: 73208, name: "[Caelid] Sellia Crystal Tunnel"});
eventflags.push({id: 73211, name: "[Consecrated Snowfield] Yelough Anix Tunnel"});
eventflags.push({id: 73410, name: "[Stormhill] Limgrave Tower Bridge"});
eventflags.push({id: 73412, name: "[Stormhill] Divine Tower of Limgrave"});
eventflags.push({id: 73420, name: "[Liurnia of the Lakes] Study Hall Entrance"});
eventflags.push({id: 73421, name: "[Liurnia of the Lakes] Liurnia Tower Bridge"});
eventflags.push({id: 73422, name: "[Liurnia of the Lakes] Divine Tower of Liurnia"});
eventflags.push({id: 73430, name: "[Capital Outskirts] Divine Tower of West Altus"});
eventflags.push({id: 73431, name: "[Capital Outskirts] Sealed Tunnel"});
eventflags.push({id: 73432, name: "[Capital Outskirts] Divine Tower of West Altus: Gate"});
eventflags.push({id: 73440, name: "[Greyoll's Dragonbarrow] Divine Tower of Caelid"});
eventflags.push({id: 73441, name: "[Greyoll's Dragonbarrow] Divine Tower of Caelid: Center"});
eventflags.push({id: 73450, name: "[Forbidden Lands] Divine Tower of East Altus: Gate"});
eventflags.push({id: 73451, name: "[Forbidden Lands] Divine Tower of East Altus"});
eventflags.push({id: 73460, name: "[Greyoll's Dragonbarrow] Isolated Divine Tower"});
eventflags.push({id: 73500, name: "[Subterranean Shunning-Grounds] Cathedral of the Forsaken"});
eventflags.push({id: 73501, name: "[Subterranean Shunning-Grounds] Underground Roadside"});
eventflags.push({id: 73502, name: "[Subterranean Shunning-Grounds] Forsaken Depths"});
eventflags.push({id: 73503, name: "[Subterranean Shunning-Grounds] Leyndell Catacombs"});
eventflags.push({id: 73504, name: "[Subterranean Shunning-Grounds] Frenzied Flame Proscription"});
eventflags.push({id: 73900, name: "[Ruin-Strewn Precipice] Magma Wyrm"});
eventflags.push({id: 73901, name: "[Ruin-Strewn Precipice] Ruin-Strewn Precipice"});
eventflags.push({id: 73902, name: "[Ruin-Strewn Precipice] Ruin-Strewn Precipice Overlook"});
eventflags.push({id: 76100, name: "[Limgrave] Church of Elleh"});
eventflags.push({id: 76101, name: "[Limgrave] The First Step"});
eventflags.push({id: 76102, name: "[Stormhill] Stormhill Shack"});
eventflags.push({id: 76103, name: "[Limgrave] Artist's Shack"});
eventflags.push({id: 76104, name: "[Limgrave] Third Church of Marika"});
eventflags.push({id: 76105, name: "[Limgrave] Fort Haight West"});
eventflags.push({id: 76106, name: "[Limgrave] Agheel Lake South"});
eventflags.push({id: 76108, name: "[Limgrave] Agheel Lake North"});
eventflags.push({id: 76110, name: "[Limgrave] Church of Dragon Communion"});
eventflags.push({id: 76111, name: "[Limgrave] Gatefront"});
eventflags.push({id: 76113, name: "[Limgrave] Seaside Ruins"});
eventflags.push({id: 76114, name: "[Limgrave] Mistwood Outskirts"});
eventflags.push({id: 76116, name: "[Limgrave] Murkwater Coast"});
eventflags.push({id: 76117, name: "[Stormhill] Saintsbridge"});
eventflags.push({id: 76118, name: "[Stormhill] Warmaster's Shack"});
eventflags.push({id: 76119, name: "[Limgrave] Summonwater Village Outskirts"});
eventflags.push({id: 76120, name: "[Limgrave] Waypoint Ruins Cellar"});
eventflags.push({id: 76150, name: "[Weeping Peninsula] Church of Pilgrimage"});
eventflags.push({id: 76151, name: "[Weeping Peninsula] Castle Morne Rampart"});
eventflags.push({id: 76152, name: "[Weeping Peninsula] Tombsward"});
eventflags.push({id: 76153, name: "[Weeping Peninsula] South of the Lookout Tower"});
eventflags.push({id: 76154, name: "[Weeping Peninsula] Ailing Village Outskirts"});
eventflags.push({id: 76155, name: "[Weeping Peninsula] Beside the Crater-Pocked Glade"});
eventflags.push({id: 76156, name: "[Weeping Peninsula] Isolated Merchant's Shack"});
eventflags.push({id: 76157, name: "[Weeping Peninsula] Bridge of Sacrifice"});
eventflags.push({id: 76158, name: "[Weeping Peninsula] Castle Morne Lift"});
eventflags.push({id: 76159, name: "[Weeping Peninsula] Behind the Castle"});
eventflags.push({id: 76160, name: "[Weeping Peninsula] Beside the Rampart Gaol"});
eventflags.push({id: 76161, name: "[Weeping Peninsula] Morne Moangrave"});
eventflags.push({id: 76162, name: "[Weeping Peninsula] Fourth Church of Marika"});
eventflags.push({id: 76200, name: "[Liurnia of the Lakes] Uld Palace Ruins"});
eventflags.push({id: 76201, name: "[Liurnia of the Lakes] Liurnia Lake Shore"});
eventflags.push({id: 76202, name: "[Liurnia of the Lakes] Laskyar Ruins"});
eventflags.push({id: 76203, name: "[Liurnia of the Lakes] Scenic Isle"});
eventflags.push({id: 76204, name: "[Liurnia of the Lakes] Academy Gate Town"});
eventflags.push({id: 76205, name: "[Liurnia of the Lakes] South Raya Lucaria Gate"});
eventflags.push({id: 76206, name: "[Liurnia of the Lakes] Main Academy Gate"});
eventflags.push({id: 76207, name: "[Bellum Highway] East Raya Lucaria Gate"});
eventflags.push({id: 76208, name: "[Bellum Highway] Bellum Church"});
eventflags.push({id: 76209, name: "[Liurnia of the Lakes] Grand Lift of Dectus"});
eventflags.push({id: 76210, name: "[Liurnia of the Lakes] Foot of the Four Belfries"});
eventflags.push({id: 76211, name: "[Liurnia of the Lakes] Sorcerer's Isle"});
eventflags.push({id: 76212, name: "[Liurnia of the Lakes] Northern Liurnia Lake Shore"});
eventflags.push({id: 76213, name: "[Liurnia of the Lakes] Road to the Manor"});
eventflags.push({id: 76214, name: "[Liurnia of the Lakes] Main Caria Manor Gate"});
eventflags.push({id: 76215, name: "[Liurnia of the Lakes] Slumbering Wolf's Shack"});
eventflags.push({id: 76216, name: "[Liurnia of the Lakes] Boilprawn Shack"});
eventflags.push({id: 76217, name: "[Liurnia of the Lakes] Artist's Shack"});
eventflags.push({id: 76218, name: "[Liurnia of the Lakes] Revenger's Shack"});
eventflags.push({id: 76219, name: "[Liurnia of the Lakes] Folly on the Lake"});
eventflags.push({id: 76220, name: "[Liurnia of the Lakes] Village of the Albinaurics"});
eventflags.push({id: 76221, name: "[Liurnia of the Lakes] Liurnia Highway North"});
eventflags.push({id: 76222, name: "[Liurnia of the Lakes] Gate Town Bridge"});
eventflags.push({id: 76223, name: "[Liurnia of the Lakes] Eastern Liurnia Lake Shore"});
eventflags.push({id: 76224, name: "[Liurnia of the Lakes] Church of Vows"});
eventflags.push({id: 76225, name: "[Liurnia of the Lakes] Ruined Labyrinth"});
eventflags.push({id: 76226, name: "[Liurnia of the Lakes] Mausoleum Compound"});
eventflags.push({id: 76227, name: "[Liurnia of the Lakes] The Four Belfries"});
eventflags.push({id: 76228, name: "[Liurnia of the Lakes] Ranni's Chamber"});
eventflags.push({id: 76229, name: "[Liurnia of the Lakes] Ravine-Veiled Village"});
eventflags.push({id: 76230, name: "[Liurnia of the Lakes] Manor Upper Level"});
eventflags.push({id: 76231, name: "[Liurnia of the Lakes] Manor Lower Level"});
eventflags.push({id: 76232, name: "[Liurnia of the Lakes] Royal Moongazing Grounds"});
eventflags.push({id: 76233, name: "[Liurnia of the Lakes] Gate Town North"});
eventflags.push({id: 76234, name: "[Liurnia of the Lakes] Eastern Tableland"});
eventflags.push({id: 76235, name: "[Liurnia of the Lakes] The Ravine"});
eventflags.push({id: 76236, name: "[Liurnia of the Lakes] Fallen Ruins of the Lake"});
eventflags.push({id: 76237, name: "[Liurnia of the Lakes] Converted Tower"});
eventflags.push({id: 76238, name: "[Liurnia of the Lakes] Behind Caria Manor"});
eventflags.push({id: 76239, name: "[Bellum Highway] Frenzied Flame Village Outskirts"});
eventflags.push({id: 76240, name: "[Bellum Highway] Church of Inhibition"});
eventflags.push({id: 76241, name: "[Liurnia of the Lakes] Temple Quarter"});
eventflags.push({id: 76242, name: "[Liurnia of the Lakes] East Gate Bridge Trestle"});
eventflags.push({id: 76243, name: "[Liurnia of the Lakes] Crystalline Woods"});
eventflags.push({id: 76244, name: "[Liurnia of the Lakes] Liurnia Highway South"});
eventflags.push({id: 76245, name: "[Liurnia of the Lakes] Jarburg"});
eventflags.push({id: 76247, name: "[Liurnia of the Lakes] Ranni's Chamber"});
eventflags.push({id: 76250, name: "[Moonlight Altar] Moonlight Altar"});
eventflags.push({id: 76251, name: "[Moonlight Altar] Cathedral of Manus Celes"});
eventflags.push({id: 76252, name: "[Moonlight Altar] Altar South"});
eventflags.push({id: 76300, name: "[Altus Plateau] Abandoned Coffin"});
eventflags.push({id: 76301, name: "[Altus Plateau] Altus Plateau"});
eventflags.push({id: 76302, name: "[Altus Plateau] Erdtree-Gazing Hill"});
eventflags.push({id: 76303, name: "[Altus Plateau] Altus Highway Junction"});
eventflags.push({id: 76304, name: "[Altus Plateau] Forest-Spanning Greatbridge"});
eventflags.push({id: 76305, name: "[Altus Plateau] Rampartside Path"});
eventflags.push({id: 76306, name: "[Altus Plateau] Bower of Bounty"});
eventflags.push({id: 76307, name: "[Altus Plateau] Road of Iniquity Side Path"});
eventflags.push({id: 76308, name: "[Altus Plateau] Windmill Village"});
eventflags.push({id: 76309, name: "[Capital Outskirts] Outer Wall Phantom Tree"});
eventflags.push({id: 76310, name: "[Capital Outskirts] Minor Erdtree Church"});
eventflags.push({id: 76311, name: "[Capital Outskirts] Hermit Merchant's Shack"});
eventflags.push({id: 76312, name: "[Capital Outskirts] Outer Wall Battleground"});
eventflags.push({id: 76313, name: "[Altus Plateau] Windmill Heights"});
eventflags.push({id: 76314, name: "[Capital Outskirts] Capital Rampart"});
eventflags.push({id: 76350, name: "[Mt. Gelmir] Bridge of Iniquity"});
eventflags.push({id: 76351, name: "[Mt. Gelmir] First Mt. Gelmir Campsite"});
eventflags.push({id: 76352, name: "[Mt. Gelmir] Ninth Mt. Gelmir Campsite"});
eventflags.push({id: 76353, name: "[Mt. Gelmir] Road of Iniquity"});
eventflags.push({id: 76354, name: "[Mt. Gelmir] Seethewater River"});
eventflags.push({id: 76355, name: "[Mt. Gelmir] Seethewater Terminus"});
eventflags.push({id: 76356, name: "[Mt. Gelmir] Craftsman's Shack"});
eventflags.push({id: 76357, name: "[Mt. Gelmir] Primeval Sorcerer Azur"});
eventflags.push({id: 76320, name: "[Altus Plateau] Shaded Castle Ramparts"});
eventflags.push({id: 76321, name: "[Altus Plateau] Shaded Castle Inner Gate"});
eventflags.push({id: 76322, name: "[Altus Plateau] Castellan's Hall"});
eventflags.push({id: 76400, name: "[Caelid] Smoldering Church"});
eventflags.push({id: 76401, name: "[Caelid] Rotview Balcony"});
eventflags.push({id: 76402, name: "[Caelid] Fort Gael North"});
eventflags.push({id: 76403, name: "[Caelid] Caelem Ruins"});
eventflags.push({id: 76404, name: "[Caelid] Cathedral of Dragon Communion"});
eventflags.push({id: 76405, name: "[Caelid] Caelid Highway South"});
eventflags.push({id: 76406, name: "[Swamp of Aeonia] Aeonia Swamp Shore"});
eventflags.push({id: 76407, name: "[Swamp of Aeonia] Astray from Caelid Highway North"});
eventflags.push({id: 76409, name: "[Caelid] Smoldering Wall"});
eventflags.push({id: 76410, name: "[Caelid] Deep Siofra Well"});
eventflags.push({id: 76411, name: "[Caelid] Southern Aeonia Swamp Bank"});
eventflags.push({id: 76412, name: "[Swamp of Aeonia] Heart of Aeonia"});
eventflags.push({id: 76413, name: "[Swamp of Aeonia] Inner Aeonia"});
eventflags.push({id: 76414, name: "[Caelid] Sellia Backstreets"});
eventflags.push({id: 76415, name: "[Caelid] Chair-Crypt of Sellia"});
eventflags.push({id: 76416, name: "[Caelid] Sellia Under-Stair"});
eventflags.push({id: 76417, name: "[Caelid] Impassable Greatbridge"});
eventflags.push({id: 76418, name: "[Caelid] Church of the Plague"});
eventflags.push({id: 76419, name: "[Caelid] Redmane Castle Plaza"});
eventflags.push({id: 76420, name: "[Caelid] Chamber Outside the Plaza"});
eventflags.push({id: 76422, name: "[Caelid] Starscourge Radahn"});
eventflags.push({id: 76450, name: "[Greyoll's Dragonbarrow] Dragonbarrow West"});
eventflags.push({id: 76451, name: "[Greyoll's Dragonbarrow] Isolated Merchant's Shack"});
eventflags.push({id: 76452, name: "[Greyoll's Dragonbarrow] Dragonbarrow Fork"});
eventflags.push({id: 76453, name: "[Greyoll's Dragonbarrow] Fort Faroth"});
eventflags.push({id: 76454, name: "[Greyoll's Dragonbarrow] Bestial Sanctum"});
eventflags.push({id: 76455, name: "[Greyoll's Dragonbarrow] Lenne's Rise"});
eventflags.push({id: 76456, name: "[Greyoll's Dragonbarrow] Farum Greatbridge"});
eventflags.push({id: 76500, name: "[Forbidden Lands] Forbidden Lands"});
eventflags.push({id: 76501, name: "[Mountaintops of the Giants] Zamor Ruins"});
eventflags.push({id: 76502, name: "[Forbidden Lands] Grand Lift of Rold"});
eventflags.push({id: 76503, name: "[Mountaintops of the Giants] Ancient Snow Valley Ruins"});
eventflags.push({id: 76504, name: "[Mountaintops of the Giants] Freezing Lake"});
eventflags.push({id: 76505, name: "[Mountaintops of the Giants] First Church of Marika"});
eventflags.push({id: 76506, name: "[Flame Peak] Giants' Gravepost"});
eventflags.push({id: 76507, name: "[Flame Peak] Church of Repose"});
eventflags.push({id: 76508, name: "[Flame Peak] Foot of the Forge"});
eventflags.push({id: 76509, name: "[Flame Peak] Fire Giant"});
eventflags.push({id: 76510, name: "[Flame Peak] Forge of the Giants"});
eventflags.push({id: 76520, name: "[Mountaintops of the Giants] Whiteridge Road"});
eventflags.push({id: 76521, name: "[Mountaintops of the Giants] Snow Valley Ruins Overlook"});
eventflags.push({id: 76522, name: "[Mountaintops of the Giants] Castle Sol Main Gate"});
eventflags.push({id: 76523, name: "[Mountaintops of the Giants] Church of the Eclipse"});
eventflags.push({id: 76524, name: "[Mountaintops of the Giants] Castle Sol Rooftop"});
eventflags.push({id: 76550, name: "[Consecrated Snowfield] Consecrated Snowfield"});
eventflags.push({id: 76551, name: "[Consecrated Snowfield] Inner Consecrated Snowfield"});
eventflags.push({id: 76652, name: "[Consecrated Snowfield] Ordina, Liturgical Town"});
eventflags.push({id: 76653, name: "[Consecrated Snowfield] Apostate Derelict"});


eventflags.push({id: 10000800, name: "Godrick the Grafted - Stormveil Castle"});
eventflags.push({id: 10000850, name: "Margit, the Fell Omen - Stormveil Castle"});
eventflags.push({id: 10010800, name: "Grafted Scion - Chapel of Anticipation"});
eventflags.push({id: 11000800, name: "Morgott, the Omen King - Leyndell"});
eventflags.push({id: 11000850, name: "Godfrey, First Elden Lord - Leyndell"});
eventflags.push({id: 11050800, name: "Hoarah Loux - Leyndell"});
eventflags.push({id: 11050850, name: "Sir Gideon Ofnir, the All-Knowing - Leyndell"});
eventflags.push({id: 12010800, name: "Dragonkin Soldier of Nokstella - Ainsel River"});
eventflags.push({id: 12010850, name: "Dragonkin Soldier - Lake of Rot"});
eventflags.push({id: 12020800, name: "Valiant Gargoyles - Siofra River"});
eventflags.push({id: 12020830, name: "Dragonkin Soldier - Siofra River"});
eventflags.push({id: 12020850, name: "Mimic Tear - Siofra River"});
eventflags.push({id: 12030390, name: "Crucible Knight Sirulia - Deeproot Depths"});
eventflags.push({id: 12030800, name: "Fia's Champion - Deeproot Depths"});
eventflags.push({id: 12030850, name: "Lichdragon Fortissax - Deeproot Depths"});
eventflags.push({id: 12040800, name: "Astel, Naturalborn of the Void - Lake of Rot"});
eventflags.push({id: 12050800, name: "Mohg, Lord of Blood - Mohgwyn Palace"});
eventflags.push({id: 12080800, name: "Ancestor Spirit - Siofra River"});
eventflags.push({id: 12090800, name: "Regal Ancestor Spirit - Nokron, Eternal City"});
eventflags.push({id: 13000800, name: "Maliketh, The Black Blade - Crumbling Farum Azula"});
eventflags.push({id: 13000830, name: "Dragonlord Placidusax - Crumbling Farum Azula"});
eventflags.push({id: 13000850, name: "Godskin Duo - Crumbling Farum Azula"});
eventflags.push({id: 14000800, name: "Rennala, Queen of the Full Moon - Academy of Raya Lucaria"});
eventflags.push({id: 14000850, name: "Red Wolf of Radagon - Academy of Raya Lucaria"});
eventflags.push({id: 15000800, name: "Malenia, Blade of Miquella - Miquella's Haligtree"});
eventflags.push({id: 15000850, name: "Loretta, Knight of the Haligtree - Miquella's Haligtree"});
eventflags.push({id: 16000800, name: "Rykard, Lord of Blasphemy - Volcano Manor"});
eventflags.push({id: 16000850, name: "Godskin Noble - Volcano Manor"});
eventflags.push({id: 16000860, name: "Abductor Virgins - Volcano Manor"});
eventflags.push({id: 18000800, name: "Ulcerated Tree Spirit - Stranded Graveyard"});
eventflags.push({id: 18000850, name: "Soldier of Godrick - Stranded Graveyard"});
eventflags.push({id: 19000800, name: "Elden Beast - Elden Throne"});
eventflags.push({id: 35000800, name: "Mohg, The Omen - Subterranean Shunning-Grounds (Leyndell)"});
eventflags.push({id: 35000850, name: "Esgar, Priest of Blood - Subterranean Shunning-Grounds (Leyndell)"});
eventflags.push({id: 39200800, name: "Magma Wyrm Makar - Ruin-Strewn Precipice (Liurnia)"});
eventflags.push({id: 30000800, name: "Cemetery Shade - Tombsward Catacombs (Limgrave)"});
eventflags.push({id: 30010800, name: "Erdtree Burial Watchdog - Impaler's Catacombs (Weeping Penisula)"});
eventflags.push({id: 30020800, name: "Erdtree Burial Watchdog - Stormfoot Catacombs (Limgrave)"});
eventflags.push({id: 30110800, name: "Black Knife Assassin - Deathtouched Catacombs (Limgrave)"});
eventflags.push({id: 30040800, name: "Grave Warden Duelist - Murkwater Catacombs (Limgrave)"});
eventflags.push({id: 30050800, name: "Cemetery Shade - Black Knife Catacombs (Liurnia)"});
eventflags.push({id: 30050850, name: "Black Knife Assassin - Black Knife Catacombs (Liurnia)"});
eventflags.push({id: 30030800, name: "Spirit-Caller Snail - Road's End Catacombs (Liurnia)"});
eventflags.push({id: 30060800, name: "Erdtree Burial Watchdog - Cliffbottom Catacombs (Liurnia)"});
eventflags.push({id: 30080800, name: "Ancient Hero of Zamor - Sainted Hero's Grave (Altus Plateau)"});
eventflags.push({id: 30090800, name: "Red Wolf of the Champion - Gelmir Hero's Grave (Mt. Gelmir)"});
eventflags.push({id: 30100800, name: "Crucible Knight Ordovis - Auriza Hero's Grave (Altus Plateau)"});
eventflags.push({id: 30100801, name: "Crucible Knight (Tree Spear) - Auriza Hero's Grave (Altus Plateau)"});
eventflags.push({id: 30120800, name: "Misbegotten Warrior - Unsightly Catacombs (Mt. Gelmir)"});
eventflags.push({id: 30120801, name: "Perfumer Tricia - Unsightly Catacombs (Mt. Gelmir)"});
eventflags.push({id: 30070800, name: "Erdtree Burial Watchdog - Wyndham Catacombs (Altus Plateau)"});
eventflags.push({id: 30130800, name: "Grave Warden Duelist - Auriza Side Tomb (Altus Plateau)"});
eventflags.push({id: 30140800, name: "Erdtree Burial Watchdog - Minor Erdtree Catacombs (Caelid)"});
eventflags.push({id: 30150800, name: "Cemetery Shade - Caelid Catacombs (Caelid)"});
eventflags.push({id: 30160800, name: "Putrid Tree Spirit - War-Dead Catacombs (Caelid)"});
eventflags.push({id: 30170800, name: "Ancient Hero of Zamor - Giant-Conquering Hero's Grave (Mountaintops)"});
eventflags.push({id: 30180800, name: "Ulcerated Tree Sprit - Giants' Mountaintop Catacombs (Mountaintops)"});
eventflags.push({id: 30190800, name: "Putrid Grave Warden Duelist - Consecrated Snowfield Catacombs (Snowfield)"});
eventflags.push({id: 30200800, name: "Stray Mimic Tear - Hidden Path to the Haligtree"});
eventflags.push({id: 31000800, name: "Patches - Murkwater Cave (Limgrave)"});
eventflags.push({id: 31010800, name: "Runebear - Earthbore Cave (Weeping Penisula)"});
eventflags.push({id: 31020800, name: "Miranda the Blighted Bloom - Tombsward Cave (Limgrave)"});
eventflags.push({id: 31030800, name: "Beastman of Farum Azula - Groveside Cave (Limgrave)"});
eventflags.push({id: 31150800, name: "Demi-Human Chief - Coastal Cave (Limgrave)"});
eventflags.push({id: 31170800, name: "Guardian Golem - Highroad Cave (Limgrave)"});
eventflags.push({id: 31040800, name: "Cleanrot Knight - Stillwater Cave (Liurnia)"});
eventflags.push({id: 31050800, name: "Bloodhound Knight - Lakeside Crystal Cave (Liurnia)"});
eventflags.push({id: 31060800, name: "Crystalians - Academy Crystal Cave (Liurnia)"});
eventflags.push({id: 31070800, name: "Kindred of Rot - Seethewater Cave (Mt. Gelmir)"});
eventflags.push({id: 31090800, name: "Demi-Human Queen Margot - Volcano Cave (Mt. Gelmir)"});
eventflags.push({id: 31180800, name: "Miranda the Blighted Bloom - Perfumer's Grotto (Altus Plateau)"});
eventflags.push({id: 31190800, name: "Black Knife Assassin - Sage's Cave (Altus Plateau)"});
eventflags.push({id: 31190850, name: "Necromancer Garris - Sage's Cave (Altus Plateau)"});
eventflags.push({id: 31210800, name: "Frenzied Duelist - Gaol Cave (Caelid)"});
eventflags.push({id: 31100800, name: "Beastman of Farum Azula - Dragonbarrow Cave (Dragonbarrow)"});
eventflags.push({id: 31200800, name: "Cleanrot Knight - Abandoned Cave (Caelid)"});
eventflags.push({id: 31110800, name: "Putrid Crystalians - Sellia Hideaway (Caelid)"});
eventflags.push({id: 31120800, name: "Misbegotten Crusader - Cave of the Forlorn (Mountaintops)"});
eventflags.push({id: 31220800, name: "Spirit-Caller Snail - Spiritcaller's Cave (Mountaintops)"});
eventflags.push({id: 32000800, name: "Scaly Misbegotten - Morne Tunnel (Weeping Penisula)"});
eventflags.push({id: 32010800, name: "Stonedigger Troll - Limgrave Tunnels (Limgrave)"});
eventflags.push({id: 32020800, name: "Crystalian (Ringblade) - Raya Lucaria Crystal Tunnel (Liurnia)"});
eventflags.push({id: 32040800, name: "Stonedigger Troll - Old Altus Tunnel (Altus Plateau)"});
eventflags.push({id: 34120800, name: "Onyx Lord - Divine Tower of West Altus (Altus Plateau)"});
eventflags.push({id: 32050800, name: "Crystalian (Ringblade) - Altus Tunnel (Altus Plateau)"});
eventflags.push({id: 32050801, name: "Crystalian (Spear) - Altus Tunnel (Altus Plateau)"});
eventflags.push({id: 32070800, name: "Magma Wyrm - Gael Tunnel (Caelid)"});
eventflags.push({id: 32080800, name: "Fallingstar Beast - Sellia Crystal Tunnel (Caelid)"});
eventflags.push({id: 32110800, name: "Astel, Stars of Darkness - Yelough Anix Tunnel (Snowfield)"});
eventflags.push({id: 34130800, name: "Godskin Apostle - Divine Tower of Caelid (Caelid)"});
eventflags.push({id: 34140850, name: "Fell Twins - Divine Tower of East Altus (Capital Outskirts)"});
eventflags.push({id: 1044360800, name: "Mad Pumpkin Head - Waypoint Ruins (Limgrave)"});
eventflags.push({id: 1043370340, name: "Night's Cavalry - Agheel Lake North (Limgrave)"});
eventflags.push({id: 1042380800, name: "Death Rite Bird - Stormgate (Limgrave)"});
eventflags.push({id: 1042380850, name: "Ball-Bearing Hunter - Warmaster's Shack (Limgrave)"});
eventflags.push({id: 1042330800, name: "Ancient Hero of Zamor - Weeping Evergaol (Weeping Penisula)"});
eventflags.push({id: 1044350800, name: "Bloodhound Knight Darriwill - Forlorn Hound Evergaol (Limgrave)"});
eventflags.push({id: 1042370800, name: "Crucible Knight - Stormhill Evergaol (Limgrave)"});
eventflags.push({id: 1043330800, name: "Erdtree Avatar - Minor Erdtree (Weeping Penisula)"});
eventflags.push({id: 1044320342, name: "Night's Cavalry - Castle Morne Approach (Weeping Penisula)"});
eventflags.push({id: 1044320340, name: "Death Rite Bird - Castle Morne Approach (Weeping Penisula)"});
eventflags.push({id: 1043300800, name: "Leonine Misbegotten - Castle Morne (Weeping Penisula)"});
eventflags.push({id: 1042360800, name: "Tree Sentinel - Church of Elleh (Limgrave)"});
eventflags.push({id: 1043360800, name: "Flying Dragon Agheel - Dragon-Burnt Ruins (Limgrave)"});
eventflags.push({id: 1045390800, name: "Tibia Mariner - Summonwater Village (Limgrave)"});
eventflags.push({id: 1034480800, name: "Royal Revenant - Kingsrealm Ruins (Liurnia)"});
eventflags.push({id: 1038410800, name: "Adan, Thief of Fire - Malefactor's Evergaol (Liurnia)"});
eventflags.push({id: 1033450800, name: "Bols, Carian Knight - Cuckoo's Evergaol (Liurnia)"});
eventflags.push({id: 1036500800, name: "Onyx Lord - Royal Grave Evergaol (Liurnia)"});
eventflags.push({id: 1033420800, name: "Alecto, Black Knife Ringleader - Moonlight Altar (Liurnia)"});
eventflags.push({id: 1033430800, name: "Erdtree Avatar - Revenger's Shack (Liurnia)"});
eventflags.push({id: 1038480800, name: "Erdtree Avatar - Minor Erdtree (Liurnia)"});
eventflags.push({id: 1035500800, name: "Royal Knight Loretta - Carian Manor (Liurnia)"});
eventflags.push({id: 1037460800, name: "Ball-Bearing Hunter - Church of Vows (Liurnia)"});
eventflags.push({id: 1039430340, name: "Night's Cavalry - Liurnia Highway Far North (Liurnia)"});
eventflags.push({id: 1036480340, name: "Night's Cavalry - East Raya Lucaria Gate (Liurnia)"});
eventflags.push({id: 1037420340, name: "Death Rite Bird - Laskyar Ruins (Liurnia)"});
eventflags.push({id: 1036450340, name: "Death Rite Bird - Gate Town Northwest (Liurnia)"});
eventflags.push({id: 1034450800, name: "Glintstone Dragon Smarag - Meeting Place (Liurnia)"});
eventflags.push({id: 1034500800, name: "Glintstone Dragon Adula - Ranni's Rise (Liurnia)"});
eventflags.push({id: 1034420800, name: "Glintstone Dragon Adula - Moonfolk Ruins (Liurnia)"});
eventflags.push({id: 1035420800, name: "Omenkiller - Village of the Albinaurics (Liurnia)"});
eventflags.push({id: 1039440800, name: "Tibia Mariner - Jarburg (Liurnia)"});
eventflags.push({id: 1037510800, name: "Ancient Dragon Lansseax - Abandoned Coffin (Altus Plateau)"});
eventflags.push({id: 1041520800, name: "Ancient Dragon Lansseax - Rampartside Path (Altus Plateau)"});
eventflags.push({id: 1038510800, name: "Demi-Human Queen - Lux Ruins (Altus Plateau)"});
eventflags.push({id: 1041500800, name: "Fallingstar Beast - South of Tree Sentinel Duo (Altus Plateau)"});
eventflags.push({id: 1040530800, name: "Sanguine Noble - Writheblood Ruins (Altus Plateau)"});
eventflags.push({id: 1041510800, name: "Tree Sentinel - Tree Sentinel Duo (Altus Plateau)"});
eventflags.push({id: 1042550800, name: "Godskin Apostle - Windmill Heights (Altus Plateau)"});
eventflags.push({id: 1040520800, name: "Black Knife Assassin - Sainted Hero's Grave Entrance (Altus Plateau)"});
eventflags.push({id: 1045520800, name: "Draconic Tree Sentinel - Capital Rampart (Capital Outskirts)"});
eventflags.push({id: 1039500800, name: "Godefroy the Grafted - Golden Lineage Evergaol (Altus Plateau)"});
eventflags.push({id: 1041530800, name: "Wormface - Woodfolk Ruins (Altus Plateau)"});
eventflags.push({id: 1039510800, name: "Night's Cavalry - Altus Highway Junction (Altus Plateau)"});
eventflags.push({id: 1044530800, name: "Death Rite Bird - Minor Erdtree (Capital Outskirts)"});
eventflags.push({id: 1043530800, name: "Ball-Bearing Hunter - Hermit Merchant's Shack (Capital Outskirts)"});
eventflags.push({id: 1037530800, name: "Demi-Human Queen - Primeval Sorcerer Azur (Mt. Gelmir)"});
eventflags.push({id: 1035530800, name: "Magma Wyrm - Seethewater Terminus (Mt. Gelmir)"});
eventflags.push({id: 1036540800, name: "Full-Grown Fallingstar Beast - Crater (Mt. Gelmir)"});
eventflags.push({id: 1039540800, name: "Elemer of the Briar - Shaded Castle (Altus Plateau)"});
eventflags.push({id: 1037540810, name: "Ulcerated Tree Spirit - Minor Erdtree (Mt. Gelmir)"});
eventflags.push({id: 1038520340, name: "Tibia Mariner - Wyndham Ruins (Altus Plateau)"});
eventflags.push({id: 1047400800, name: "Putrid Avatar - Minor Erdtree (Caelid)"});
eventflags.push({id: 1048370800, name: "Decaying Ekzykes - Caelid Highway South (Caelid)"});
eventflags.push({id: 1048400800, name: "Monstrous Dog - Southwest of Caelid Highway South (Caelid)"});
eventflags.push({id: 1049370800, name: "Night's Cavalry - Southern Aeonia Swamp Bank (Caelid)"});
eventflags.push({id: 1049370850, name: "Death Rite Bird - Southern Aeonia Swamp Bank (Caelid)"});
eventflags.push({id: 1049380800, name: "Commander O'Neil - East Aeonia Swamp (Caelid)"});
eventflags.push({id: 1051360800, name: "Crucible Knight - Redmane Castle (Caelid)"});
eventflags.push({id: 1052380800, name: "Starscourge Radahn - Battlefield (Caelid)"});
eventflags.push({id: 1049390800, name: "Nox Priest - West Sellia (Caelid)"});
eventflags.push({id: 1048410800, name: "Ball-Bearing Hunter - Isolated Merchant's Shack (Dragonbarrow)"});
eventflags.push({id: 1049390850, name: "Battlemage Hugues - Sellia Crystal Tunnel Entrance (Caelid)"});
eventflags.push({id: 1051400800, name: "Putrid Avatar - Dragonbarrow Fork (Caelid)"});
eventflags.push({id: 1052410800, name: "Flying Dragon Greyll - Dragonbarrow (Caelid)"});
eventflags.push({id: 1052410850, name: "Night's Cavalry - Dragonbarrow (Caelid)"});
eventflags.push({id: 1051430800, name: "Black Blade Kindred - Bestial Sanctum (Caelid)"});
eventflags.push({id: 1048510800, name: "Night's Cavalry - Forbidden Lands (Mountaintops)"});
eventflags.push({id: 1049520800, name: "Black Blade Kindred - Before Grand Lift of Rold (Mountaintops)"});
eventflags.push({id: 1054560800, name: "Borealis the Freezing Fog - Freezing Fields (Mountaintops)"});
eventflags.push({id: 1053560800, name: "Roundtable Knight Vyke - Lord Contender's Evergaol (Mountaintops)"});
eventflags.push({id: 1052520800, name: "Fire Giant - Giant's Forge (Mountaintops)"});
eventflags.push({id: 1052560800, name: "Erdtree Avatar - Minor Erdtree (Mountaintops)"});
eventflags.push({id: 1050570800, name: "Death Rite Bird - West of Castle So (Mountaintops)"});
eventflags.push({id: 1050570850, name: "Putrid Avatar - Minor Erdtree (Snowfield)"});
eventflags.push({id: 1051570800, name: "Commander Niall - Castle Soul (Mountaintops)"});
eventflags.push({id: 1050560800, name: "Great Wyrm Theodorix - Albinauric Rise (Mountaintops)"});
eventflags.push({id: 1248550800, name: "Night's Cavalry - Sourthwest (Mountaintops)"});
eventflags.push({id: 1048570800, name: "Death Rite Bird - Ordina, Liturgical Town (Snowfield)"});

export { eventflags as default };